[package]
name = "eslauncher2"
version = "0.1.0"
authors = ["M*C*O <mcofficer@gmx.de>"]
edition = "2018"

[dependencies]
serde = "^1.0"
serde_derive = "^1.0"
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.10", features = ["json",  "rustls-tls", "blocking"] }
flate2 = "1.0"
tar = "0.4"
zip-extensions = "0.4"
nfd2 = "0.2.0"
rodio = { version="0.11", features=["vorbis"], default_features=false }
rust-embed="5.5"