[package]
name = "eslauncher2"
version = "0.3.1"
authors = ["M*C*O <mcofficer@gmx.de>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
bitar = { version="0.6.4", features=["rustls-tls"] }
chrono = { version = "0.4", features = ["serde"] }
espim = { path="espim" }
flate2 = "1.0"
futures = "0.3"
log = { version="0.4.8", features=["std"] }
open = "1"
platform-dirs = "0.2.0"
progress-streams = "1.1.0"
reqwest = { version="0.10", default_features = false, features=["rustls-tls"] }
rodio = { version="0.11", default_features = false, features=["vorbis"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-xml-rs = "0.4"
tar = "0.4"
tokio = { version="0.2", default_features = false, features=["fs"] }
ureq = { version = "1.0", default_features = false, features = ["json", "tls"] }
version = "3"
zip-extensions = "0.4"

[dependencies.iced]
version = "0.1.1"
default_features = false
features = ["image"]
# TODO: consider features = ["async-std"]

[dev-dependencies.iced]
version = "0.1.1"
default_features = false
features = ["debug", "image"]

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true