[package]
name = "eslauncher2"
version = "0.1.0"
authors = ["M*C*O <mcofficer@gmx.de>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.51"
chrono = { version = "0.4", features = ["serde"] }
ureq = { version = "0.12", features = ["json", "tls"], default_features=false }
flate2 = "1.0"
tar = "0.4"
zip-extensions = "0.4"
nfd2 = "0.2.0"
rodio = { version="0.11", features=["vorbis"], default_features=false }
iced = "0.1.1"
iced_native = "0.2.1"
iced_futures = "0.1.1"
futures-core = "0.3.4"

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true