[package]
name = "eslauncher2"
version = "0.1.0"
authors = ["M*C*O <mcofficer@gmx.de>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.51"
chrono = { version = "0.4", features = ["serde"] }
ureq = { version = "0.12", features = ["json", "tls"], default_features=false }
flate2 = "1.0"
tar = "0.4"
zip-extensions = "0.4"
platform-dirs = "0.2.0"
rodio = { version="0.11", features=["vorbis"], default_features=false }
iced = "0.1.1"
log = { version="0.4.8", features=["std"] }
progress-streams = "1.1.0"
bitar = { version="0.6.2", features=["rustls-tls"]}
url = "2.1"
tokio = { version="0.2", features=["fs"] }
futures = "0.3"
anyhow = "1.0"
git-version = "0.3"

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true