[package]
name = "eslauncher2"
version = "0.3.1"
authors = ["M*C*O <mcofficer@gmx.de>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-xml-rs = "0.4"
ureq = { version = "0.12", features = ["json", "tls"], default_features=false }
flate2 = "1.0"
tar = "0.4"
zip-extensions = "0.4"
platform-dirs = "0.2.0"
rodio = { version="0.11", features=["vorbis"], default_features=false }
iced = "0.1.1"
log = { version="0.4.8", features=["std"] }
progress-streams = "1.1.0"
bitar = { version="0.6.4", features=["rustls-tls"] }
reqwest = { version="0.10", features=["rustls-tls"], default_features=false }
tokio = { version="0.2", features=["fs"] }
futures = "0.3"
anyhow = "1.0"
open = "1"
version = "3"

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true