name: Build
on:
  push:
    branches:
      - master
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
      - name: Install cargo-deb
        run: cargo install cargo-deb
      - uses: actions/checkout@master
      - name: Build binary
        run: cargo build --verbose --release
      - name: Strip binary
        run: strip target/release/eslauncher2
      - name: Archive binary
        uses: actions/upload-artifact@v1
        with:
          name: eslauncher2-x86_64-unknown-linux-gnu
          path: target/release/eslauncher2

  windows:
    runs-on: windows-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
      - uses: actions/checkout@master
      - name: Enable static CRT linkage
        run: |
          mkdir .cargo
          echo '[target.x86_64-pc-windows-msvc]' >> .cargo/config
          echo 'rustflags = ["-Ctarget-feature=+crt-static"]' >> .cargo/config
      - name: Build binary
        run: cargo build --verbose --release
      - name: Archive binary
        uses: actions/upload-artifact@v1
        with:
          name: eslauncher2-x86_64-pc-windows-msvc
          path: target/release/eslauncher2.exe

  macos:
    runs-on: macOS-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
      - uses: actions/checkout@master
      - name: Enable Link Time Optimizations
        run: |
          echo "[profile.release]" >> Cargo.toml
          echo "lto = true" >> Cargo.toml
      - name: Build binary
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.14
        run: cargo build --verbose --release
      - name: Strip binary
        run: strip target/release/eslauncher2
      - name: Archive binary
        uses: actions/upload-artifact@v1
        with:
          name: eslauncher2-x86_64-apple-darwin
          path: target/release/eslauncher2
